# Jekyll shit, dont mess with the configs here, please
theme: jekyll-theme-midnight
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
webmaster_verifications:
  google: BMngFuhCFgzanbXj-TANEkNmNq2GACXdYNLhTnDUXFA # IF YOU ARE FORKING, REMOVE THIS VALUE!!! (or put your own)
social:
  name: PatoFlamejanteTV
  links:
    - https://github.com/PatoFlamejanteTV
    - https://x.com/pato_flamejante
    - https://www.youtube.com/@patoflamejantetv_ofc
defaults:
  -
    scope:
      path:            "*.*" # Scary! Actually, you should have extreme caution with this btw.
    values:
      sitemap:         true
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-FE30WSCDLJ # IF YOU ARE FORKING, REMOVE THIS VALUE!!! (or put your own)
