# Jekyll shit, dont mess with the configs here, please
theme: jekyll-theme-midnight
plugins:
  - jekyll-seo-tag
webmaster_verifications:
  google: BMngFuhCFgzanbXj-TANEkNmNq2GACXdYNLhTnDUXFA
  bing: 1234
