# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (every 30 minutes (yes, an GitHub profile can have a bunch of activity))
  schedule: [{cron: "*/30 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: PatoFlamejanteTV
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Brazil, America/Sao_Paulo
         #plugin_16personalities: yes
         #plugin_16personalities_url: ${{ secrets.SIXTEEN_PERSONALITIES_URL }}
         #plugin_16personalities_sections: personality, traits
         #plugin_16personalities_scores: no
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_self: yes # Include own repositories
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 7
          plugin_habits_facts: yes
          plugin_habits_from: 14
          plugin_habits_languages_limit: 0
         #plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
         #plugin_languages_categories: markup, programming
          plugin_languages_colors: github
         #plugin_languages_limit: 12
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 7
          plugin_languages_recent_load: 10
          plugin_languages_sections: most-used
         #plugin_languages_threshold: 0%
          plugin_languages_indepth: no # i suspect that THIS line is making my life a mf mess
          plugin_languages_details: bytes-size, percentage, lines

          # This part below will ignore my decomps/leak mirrors from displaying as "code i made"
          repositories_skipped: >-
            PatoFlamejanteTV/ROBLOX,
            PatoFlamejanteTV/WindowsNT3.5Code, 
            PatoFlamejanteTV/WindowsEmbedCE6Code,
            PatoFlamejanteTV/undertale, 
            PatoFlamejanteTV/SamsungAntiPhishingDemo, 
            PatoFlamejanteTV/SamsungSecureStorage, 
            PatoFlamejanteTV/SamsungSecureWifi,
            PatoFlamejanteTV/BadPiggies-decompile,
            PatoFlamejanteTV/60SecondsReatomized-decompile,
            PatoFlamejanteTV/UltraKill-decompile,
            PatoFlamejanteTV/Infinitode2-decompile,
            PatoFlamejanteTV/KineDecomp,
            PatoFlamejanteTV/Infinitode2-mobile-decompile,
            PatoFlamejanteTV/Infinitode2-JADXDecomp,
            PatoFlamejanteTV/Infinitode2-UnDecompiled,
            PatoFlamejanteTV/flipaclip-4-1-2
            PatoFlamejanteTV/AlightMotionDecomp
          plugin_languages_ignored: >-
             smali, java, html
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          plugin_stargazers_days: 7
          plugin_starlists: yes
          plugin_starlists_limit: 0
          plugin_starlists_limit_languages: 0
          plugin_starlists_limit_repositories: 4
          plugin_starlists_shuffle_repositories: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_topics: yes
          plugin_topics_limit: 7
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          plugin_poopmap_token: ${{ secrets.POOPMAP_TOKEN }}
          plugin_poopmap: yes
          plugin_screenshot: yes
          plugin_screenshot_title: XKCD of the day
          plugin_screenshot_url: https://xkcd.com
          plugin_screenshot_selector: "#comic img"
