# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (every 45 minutes (yes, an GitHub profile can have a bunch of activity))
  schedule: [{cron: "*/45 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: PatoFlamejanteTV
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Brazil, America/Sao_Paulo
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          plugin_notable: yes
          plugin_notable_from: all
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 7
          plugin_habits_facts: yes
          plugin_habits_from: 7
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: css, smali, java, html
          plugin_languages_details: percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_discussions: yes
          # This part below will ignore my decomps/leak mirrors from displaying as "code i made"
          repositories_skipped: >-
            PatoFlamejanteTV/ROBLOX,
            PatoFlamejanteTV/WindowsNT3.5Code, 
            PatoFlamejanteTV/WindowsEmbedCE6Code,
            PatoFlamejanteTV/undertale, 
            PatoFlamejanteTV/SamsungAntiPhishingDemo, 
            PatoFlamejanteTV/SamsungSecureStorage, 
            PatoFlamejanteTV/SamsungSecureWifi,
            PatoFlamejanteTV/BadPiggies-decompile,
            PatoFlamejanteTV/60SecondsReatomized-decompile,
            PatoFlamejanteTV/UltraKill-decompile,
            PatoFlamejanteTV/Infinitode2-decompile,
            PatoFlamejanteTV/KineDecomp,
            PatoFlamejanteTV/Infinitode2-mobile-decompile,
            PatoFlamejanteTV/Infinitode2-JADXDecomp,
            PatoFlamejanteTV/Infinitode2-UnDecompiled,
            PatoFlamejanteTV/flipaclip-4-1-2
            PatoFlamejanteTV/AlightMotionDecomp
          plugin_poopmap_token: ${{ secrets.POOPMAP_TOKEN }}
          plugin_poopmap: yes
